### PR TITLE
Use --with-privsep-path

### PR DESCRIPTION
**Pull request by awaw**

### CODE REVIEW

**Comment by bcook-r7** [comment]
Thanks, but the current behavior is intentional and explained further in issue #6.

In case I missed something, what is the benefit of hardcoding the path in the binary vs just using the homedir of the ntpd user? Would it make more sense to just remove the option, if it is confusing?

**Comment by awaw** [comment]
Yes, I found the behaviour confusing because the INSTALL file says:

```
Normally ntpd will always use the home directory of the privsep user
to chroot to, however use of this option will cause ntpd to always
use the specified directory.
```

I can live without the option. I was building some new RPMs for our infrastructure and thought it would help to migrate from /var/empty/ntp to /var/empty.

**Comment by bcook-r7** [comment]
Ah, I overlooked that part when migrating the INSTALL file from OpenNTPD 3.9p1, thanks. It did have this behavior in <= 3.9p1.

I'm leaning toward removing the knob so there are fewer ways to shoot oneself in the foot, but I will ask Darren what the driver was for this option. Thanks again.

**Comment by awaw** [comment]
btw, portable OpenSSH uses --with-privsep-path like described in INSTALL

**Pull request closed without merging**
